# Generated by Django 4.2.3 on 2023-08-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_spotifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='last_refreshed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
