# Generated by Django 4.2.3 on 2023-07-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Option1', 'Option 1'), ('Option2', 'Option 2')], max_length=10)),
            ],
        ),
    ]
