# Generated by Django 4.2.5 on 2023-09-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0003_remove_completedlist_albums_remove_todolist_albums_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedlist',
            old_name='album',
            new_name='albums',
        ),
        migrations.AddField(
            model_name='todolist',
            name='albums',
            field=models.ManyToManyField(related_name='to_do_list_albums', to='album_app.album'),
        ),
    ]
