# Generated by Django 4.2.3 on 2023-08-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0003_alter_spotifytoken_last_refreshed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='expires_in',
            new_name='expires_at',
        ),
    ]
