# Generated by Django 4.2.5 on 2024-04-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0005_song_primary_artist_alter_song_duration_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist_id', models.CharField(max_length=255)),
            ],
        ),
    ]
