# Generated by Django 4.2.5 on 2024-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0007_inputalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Omit_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='InputAlbum',
        ),
        migrations.AddField(
            model_name='input_artist',
            name='language',
            field=models.CharField(default='English', max_length=255),
        ),
    ]
