# Generated by Django 4.2.5 on 2024-04-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0010_alter_last_update_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_artist',
            name='language',
            field=models.CharField(max_length=255),
        ),
    ]
