# Generated by Django 4.2.5 on 2024-04-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0011_alter_input_artist_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_artist',
            name='language',
        ),
    ]
