# Generated by Django 4.2.5 on 2024-04-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0012_remove_input_artist_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_artist',
            name='language',
            field=models.CharField(default='English', max_length=255),
            preserve_default=False,
        ),
    ]
