# Generated by Django 4.2.5 on 2024-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0013_input_artist_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_artist',
            name='language',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
