# Generated by Django 4.2.5 on 2024-04-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0015_input_artist_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='done',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
