# Generated by Django 4.2.5 on 2024-04-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0016_album_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='done',
        ),
        migrations.AddField(
            model_name='input_album',
            name='done',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
