# Generated by Django 4.2.5 on 2024-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0017_remove_album_done_input_album_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='last_update',
            name='date_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='input_album',
            name='done',
            field=models.IntegerField(default=0),
        ),
    ]
